---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ccd
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ccd
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}-ccd
    app.kubernetes.io/instance: {{ .Release.Name }}-ccd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: user-profile-api-{{ required "`ingressHost` must be set in your values.yaml file" (tpl .Values.ingressHost $) }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-user-profile-api
          servicePort: 80
  {{- if .Values.caseManagementWeb.enabled }}
  - host: case-management-web-{{ tpl .Values.ingressHost $ }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-case-management-web
          servicePort: 80
  {{- end }}
  {{- if .Values.adminWeb.enabled }}
  - host: admin-web-{{ tpl .Values.ingressHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-admin-web
          servicePort: 80
  {{- end }}
  {{- if .Values.printApi.enabled }}
  - host: print-api-{{ tpl .Values.ingressHost $ }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-print-api
          servicePort: 80
  {{- end }}
  - host: data-store-api-{{ tpl .Values.ingressHost $ }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-data-store-api
          servicePort: 80
  - host: definition-store-api-{{ tpl .Values.ingressHost $ }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-definition-store-api
          servicePort: 80

