java:
  image: hmcts.azurecr.io/hmcts/ccd-user-profile-api:latest
  applicationPort: 4453
  environment:
    IDAM_S2S_URL: "http://rpe-service-auth-provider-saat.service.core-compute-saat.internal"
    USER_PROFILE_S2S_AUTHORISED_SERVICES: "ccd_data,ccd_definition,ccd_admin"
    APPINSIGHTS_INSTRUMENTATIONKEY: 'fake-key'
    USER_PROFILE_DB_HOST: bulk-scan-orchestrator-pr-1-postgresql
    USER_PROFILE_DB_PORT: 5432
    USER_PROFILE_DB_NAME: hmcts
    USER_PROFILE_DB_USERNAME: hmcts
    USER_PROFILE_DB_PASSWORD: hmcts
    USER_PROFILE_DB_USE_SSL: false
  # Don't modify below here
  #serviceName: ${SERVICE_NAME}
  #ingressHost: 
  
postgresql:
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: hmcts
  persistence:
    enabled: false